### ISSUE TITLE
Adding LiveATC to complement LiveTraffic

### ISSUE THREAD

**Issue by Gyroplaneguy** [TwinFan/PlayLiveATC#1]
**Current Situation / Problem**
What does the current situation, processing, behaviour, problem look like?
You have to manually launch appropriate LiveATC file to match your location, either airport, atis, center or approach.

**Suggested Solution**
A plugin (either as part of LiveTraffic, standalone, or even just a LUA script) that would launch appropriate file in VLC player via command line.

Example for KSFO:
On liveatc site if you search for KSFO you will see multiple feeds based on frequency.  Tower is 120.5.  If you click on the green box to listen in MP3 player (assumes VLC is set as defualt player) it will download a *.pls file.  In this case ksfo_twr.pls.  My idea would be to have the user download these files ahead of time and put them in an "active folder" and rename the file to match the frequency, i.e. 1205.pls. 

The plugin or script could then check the Com1/2 frequency and when changed to 120.5 it could check to see if you have a matching file and then launch the command line:
% vlc 1205.pls --audio-desync=90000 (this is the delay time to match the LiveTraffic buffer) 

Here is a link to VLC command line wiki:
https://wiki.videolan.org/Documentation:Command_line/

One of the challenges is that the same frequencies can be used by multiple airports, so again you would either need to build some logic to check your current location and look for the closest airport that uses that frequency, or the user would have to ensure the correct files were in the "active folder" for the area they plan to fly in.  I would be fine with the basic method as a start.

I am sure there is a more elegant solution that could be built to automatically search the liveatc.net site based on your current location, but I was trying to keep it simple as I don't believe liveatc.net offers any type of api.

**Alternatives**
Here is a similar implementation that was done for P3D.  I tried reaching out to the author to see if he would consider porting to xplane or sharing his code, but I received no reply.

http://laap.atc.free.fr/accueil-en.php

**Benefits**
Why do you think an enhancement is necessary / beneficial?
Why should anyone invest the effort of implementing and testing it ;) ?

**Additional context**
Add any other context like log file/extract or screenshots about the feature request here.

Thanks again.  LiveTraffic is great.  As a real world pilot, other than PilotEdge where you can interact with a live controller, I think LiveTraffic and LiveATC.net combined is really a game changer for Xplane.  There is nothing better than the real thing.

Unfortunately, I am not a programmer so I will be of limited help in contributing to the code.  But I would be a willing and active beta tester.

Best regards.

Jim

**Comment by TwinFan** [comment]
Starting/stopping `VLC` should be pretty much under control now, even two in parallel for 2 COM frequencies:
```
SwitchLiveATC 14-May 23:09:18Z INFO  SwitchLiveATC.cpp:202/SLAFlightLoopCB: COM2 is now 118.000
SwitchLiveATC 14-May 23:09:18Z DEBUG SLARunVLC.cpp:105/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/kjfk_twr.pls
SwitchLiveATC 14-May 23:09:18Z DEBUG SLARunVLC.cpp:168/StartStream: pid is 5139 for url 'https://www.liveatc.net/play/kjfk_twr.pls'
SwitchLiveATC 14-May 23:09:29Z INFO  SwitchLiveATC.cpp:202/SLAFlightLoopCB: COM1 is now 128.800
SwitchLiveATC 14-May 23:09:29Z DEBUG SLARunVLC.cpp:105/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 14-May 23:09:29Z DEBUG SLARunVLC.cpp:168/StartStream: pid is 5140 for url 'https://www.liveatc.net/play/ksfo_twr.pls'
SwitchLiveATC 14-May 23:09:51Z DEBUG SLARunVLC.cpp:208/StopStream: killing pid 5140 for url https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 14-May 23:10:01Z INFO  SwitchLiveATC.cpp:202/SLAFlightLoopCB: COM1 is now 128.800
SwitchLiveATC 14-May 23:10:01Z DEBUG SLARunVLC.cpp:105/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 14-May 23:10:02Z DEBUG SLARunVLC.cpp:168/StartStream: pid is 5141 for url 'https://www.liveatc.net/play/ksfo_twr.pls'
SwitchLiveATC 14-May 23:10:18Z DEBUG SLARunVLC.cpp:208/StopStream: killing pid 5141 for url https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 14-May 23:10:18Z DEBUG SLARunVLC.cpp:208/StopStream: killing pid 5139 for url https://www.liveatc.net/play/kjfk_twr.pls
```
Now we have to turn to figuring out the _actual_ url, which so far is still just a hard-coded test.

**Comment by TwinFan** [comment]
Querying LiveATC for all streams by frequency and parsing the result works:
```
SwitchLiveATC 18-May 21:52:32Z INFO  SLACOMChannel.cpp:97/StartStream: COM2 is now 120.500
SwitchLiveATC 18-May 21:52:32Z DEBUG SLACOMChannel.cpp:395/QueryLiveATC: Sending query https://www.liveatc.net/search/f.php?freq=120.500
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:354/ParseForAirportStreams: Adding    stream CYEG|CYEG Approach|1|https://www.liveatc.net/play/cyeg_app.pls
...
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:321/ParseForAirportStreams: Stream KBUF Tower skipped as it is not UP but 'DOWN'
...
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:354/ParseForAirportStreams: Adding    stream KSFO|KSFO Tower/Ground|4|https://www.liveatc.net/play/ksfo_twr2.pls
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:348/ParseForAirportStreams: Replacing stream KSFO|KSFO Tower|2|https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:354/ParseForAirportStreams: Adding    stream LFPO|LFPO Tower|2|https://www.liveatc.net/play/lfpo3_twr.pls
...
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:223/StopStream: killing pid 20473 for url https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 18-May 21:52:33Z DEBUG SLACOMChannel.cpp:115/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/ksfo_twr.pls
SwitchLiveATC 18-May 21:52:34Z DEBUG SLACOMChannel.cpp:178/StartStream: pid is 20476 for url 'https://www.liveatc.net/play/ksfo_twr.pls'
```
Stream status is taken into account. (But when it's `DOWN` then there is no URL either.)

`Replacing` happens when there are multiple streams per airport: The stream with the lowest number of lines in the "facilities" table wins as it is the most specific stream.

**Comment by TwinFan** [comment]
Of the airports returned by LiveATC, finding the closest now works, including monitoring its distance dynamically, getting out of or back in reach:
```
SwitchLiveATC 19-May 22:05:12Z DEBUG SLACOMChannel.cpp:447/QueryLiveATC: Sending query https://www.liveatc.net/search/f.php?freq=128.725
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:380/ParseForAirportStreams: Adding    stream ESOW|ESOW Twr/CTAF/Control|21|https://www.liveatc.net/play/esow.pls
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:380/ParseForAirportStreams: Adding    stream KAFW|KAFW Clearance/Ground|2|https://www.liveatc.net/play/kafw3_1.pls
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:380/ParseForAirportStreams: Adding    stream KBMI|KBMI Gnd/Twr/App/Dep|3|https://www.liveatc.net/play/kbmi.pls
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:380/ParseForAirportStreams: Adding    stream KJFK|KJFK D-ATIS|1|https://www.liveatc.net/play/kjfk_atis.pls
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:424/FindClosestAirport: Closest airport is KJFK (18.0nm)
SwitchLiveATC 19-May 22:05:13Z INFO  SLACOMChannel.cpp:125/StartStream: COM2 is now 128.725, tuning to 'KJFK D-ATIS'
SwitchLiveATC 19-May 22:05:13Z DEBUG SLACOMChannel.cpp:139/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/kjfk_atis.pls
SwitchLiveATC 19-May 22:05:14Z DEBUG SLACOMChannel.cpp:202/StartStream: pid is 1594 for url 'https://www.liveatc.net/play/kjfk_atis.pls'
...
SwitchLiveATC 19-May 22:05:32Z DEBUG SLACOMChannel.cpp:424/FindClosestAirport: Closest airport is KJFK (18.0nm)
SwitchLiveATC 19-May 22:05:32Z INFO  SLACOMChannel.cpp:125/StartStream: COM2 is now 121.650, tuning to 'KJFK Ground'
SwitchLiveATC 19-May 22:05:32Z DEBUG SLACOMChannel.cpp:249/StopStream: killing pid 1594 for url https://www.liveatc.net/play/kjfk_gnd.pls
SwitchLiveATC 19-May 22:05:32Z DEBUG SLACOMChannel.cpp:139/StartStream: Will run: /Applications/VLC.app/Contents/MacOS/VLC -Idummy --audio-desync=0 https://www.liveatc.net/play/kjfk_gnd.pls
SwitchLiveATC 19-May 22:05:33Z DEBUG SLACOMChannel.cpp:202/StartStream: pid is 1598 for url 'https://www.liveatc.net/play/kjfk_gnd.pls'
...
SwitchLiveATC 19-May 22:10:27Z INFO  SLACOMChannel.cpp:104/CheckComDistance: 'KJFK Ground' now out of reach
SwitchLiveATC 19-May 22:10:27Z DEBUG SLACOMChannel.cpp:249/StopStream: killing pid 1598 for url https://www.liveatc.net/play/kjfk_gnd.pls
```

**Comment by Gyroplaneguy** [comment]
Getting excited, the number of unchecked boxes is getting smaller.  Looking forward to testing.

Jim
