### ISSUE TITLE
Windows build: Could not init VLC: Wrapping a NULL instance

### ISSUE THREAD

**Issue by dmstumpf** [TwinFan/PlayLiveATC#7]
Still seeing error during plugin init under Windows:

PlayLiveATC 13-Jun 04:39:31Z ERROR Src\PLACOMChannel.cpp:81/CreateVLCInstance: Could not init VLC: Wrapping a NULL instance

**Comment by TwinFan** [comment]
https://forums.x-plane.org/index.php?/forums/topic/176845-tip-to-fix-audio-sync-with-liveatc/&do=findComment&comment=1681494
